import type { GameSessionDto } from '@api';

export const mockGameSessionResponse: GameSessionDto = {
  id: 1,
  userId: 1,
  bag: {
    id: 1,
    name: '여행용 백팩',
    code: 'backpack',
    image: '/bag.png',
    capacity: 100,
    description: '여행하기 좋은 중형 백팩입니다.',
  },
  bagCapacityUsed: 10,
  bagConfirmedAt: '2024-01-01T00:00:00Z',
  status: 'ACTIVE',
  lifePoint: 100,
  currentDayId: 1,
  currentActId: 1,
  endingId: null,
  endedAt: null,
  createdAt: '2024-01-01T00:00:00Z',
  updatedAt: '2024-01-01T00:00:00Z',
  gameSessionInventory: [],
  playingCharacterSet: {
    id: 1,
    gameSessionId: 1,
    characterGroupId: 1,
    playingCharacter: [
      {
        id: 1,
        playingCharacterSetId: 1,
        characterId: 1,
        character: {
          id: 1,
          code: 'john',
          name: 'John Doe',
          age: 25,
          description: 'A brave character',
          selectImage: 'https://example.com/image.png',
          portraitImage: 'https://example.com/image.png',
          defaultHp: 100,
          defaultMental: 100,
          bgColor: '#000000',
          borderColor: '#000000',
        },
        currentHp: 80,
        currentMental: 70,
      },
      {
        id: 2,
        playingCharacterSetId: 1,
        characterId: 2,
        character: {
          id: 2,
          code: 'jane',
          name: 'Jane Doe',
          age: 23,
          description: 'A smart character',
          selectImage: 'https://example.com/image.png',
          portraitImage: 'https://example.com/image.png',
          defaultHp: 100,
          defaultMental: 100,
          bgColor: '#000000',
          borderColor: '#000000',
        },
        currentHp: 90,
        currentMental: 85,
      },
    ],
  },
};

export const mockEmptyGameSessionResponse: GameSessionDto = {
  id: 2,
  userId: 1,
  bag: {
    id: 0,
    name: '기본 가방',
    code: 'default',
    image: '/bag.png',
    capacity: 50,
    description: '기본으로 제공되는 가방입니다.',
  },
  bagCapacityUsed: null,
  bagConfirmedAt: null,
  status: 'PENDING',
  lifePoint: 100,
  currentDayId: null,
  currentActId: null,
  endingId: null,
  endedAt: null,
  createdAt: '2024-01-01T00:00:00Z',
  updatedAt: '2024-01-01T00:00:00Z',
  playingCharacterSet: null,
  gameSessionInventory: [],
};
